import { useNavigate } from "react-router-dom";
import { ArrowLeft, DollarSign, TrendingUp, Package, Calculator, FileText, Briefcase } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/PageHeader";
import { SectionHeading } from "@/components/ui/SectionHeading";

const Glossary = () => {
  const navigate = useNavigate();

  const financialTerms = [
    {
      term: "Revenue / Sales",
      definition: "Total money received from selling cards before any deductions. This is the gross amount you collect from customers.",
      example: "If you sell a card for $100, that's $100 in revenue."
    },
    {
      term: "Gross Profit",
      definition: "Revenue minus cost of goods sold (COGS). This shows profit before accounting for business expenses like show tables, gas, or supplies.",
      example: "Buy card for $20, sell for $100 = $80 gross profit."
    },
    {
      term: "Net Profit",
      definition: "Gross profit minus all business expenses (table costs, travel, supplies, etc.). This is your actual business profit after all costs.",
      example: "Gross profit $80 - $15 show table - $10 gas = $55 net profit."
    },
    {
      term: "Business Revenue",
      definition: "Total money generated by business operations. This is all sales revenue from shows, bulk sales, and online channels.",
      example: "All card sales for the month = Business Revenue."
    },
    {
      term: "Personal Income / Owner's Draw",
      definition: "Money you take from the business for personal use. This is what you actually earn as salary. Not the same as business revenue.",
      example: "Business makes $5,000 revenue, but you only take $3,000 for personal expenses."
    },
    {
      term: "Cash Flow",
      definition: "Money moving in and out of your business. Positive cash flow means more coming in than going out. Critical for staying in business.",
      example: "Buy $500 lot, sell cards for $1,200 = $700 positive cash flow."
    },
    {
      term: "Profit Margin",
      definition: "Net profit as a percentage of revenue. Shows how much of each dollar you keep as profit.",
      example: "$100 revenue - $40 total costs = $60 profit = 60% margin."
    },
    {
      term: "ROI (Return on Investment)",
      definition: "Profit as a percentage of money invested. Measures how well your investment performs.",
      example: "Invest $100 in a lot, profit $150 = 150% ROI."
    },
    {
      term: "Break-Even Point",
      definition: "Point where total revenue equals total costs. After this, you start making profit.",
      example: "Show table costs $75. Need to sell enough cards to make $75 revenue to break even."
    }
  ];

  const inventoryTerms = [
    {
      term: "Cost Basis / COGS",
      definition: "What you originally paid for inventory (Cost of Goods Sold). Essential for calculating profit accurately.",
      example: "Buy lot for $200 with 100 cards = $2 cost basis per card."
    },
    {
      term: "Inventory Turnover",
      definition: "How quickly you convert inventory into cash. Fast turnover = more profit cycles. Better to sell quickly at 30% margin than slowly at 100%.",
      example: "Sell entire lot in 1 month = 12x yearly turnover vs. 1 year = 1x turnover."
    },
    {
      term: "Average Sale Price",
      definition: "Total revenue divided by number of sales. Helps predict future revenue and set goals.",
      example: "10 sales totaling $500 = $50 average sale price."
    },
    {
      term: "Markup",
      definition: "Difference between selling price and cost basis. Usually expressed as percentage or multiplier.",
      example: "Buy for $20, sell for $60 = $40 markup = 200% markup (3x multiplier)."
    },
    {
      term: "Lot",
      definition: "Group purchase of multiple cards bought together. Usually from estate sales, storage auctions, or bulk purchases.",
      example: "Buy collection of 500 cards for $300 = one lot."
    },
    {
      term: "Premium Cards",
      definition: "High-value individual cards worth selling separately. These typically have better margins but require more market knowledge.",
      example: "Rare rookie card worth $200+ sold individually at show."
    },
    {
      term: "Bulk Sales",
      definition: "Selling multiple cards together at once, usually to dealers or collectors. Lower margins but faster cash conversion.",
      example: "Sell 50 common cards to dealer for $100 total."
    }
  ];

  const taxTerms = [
    {
      term: "Business Expenses",
      definition: "Costs to run your business that are tax-deductible. Keep receipts! These reduce your taxable income.",
      example: "Show table fees, gas, supplies, storage, packaging materials."
    },
    {
      term: "Self-Employment Tax",
      definition: "Extra 15.3% tax on business profits (covers Social Security and Medicare). Paid in addition to regular income tax.",
      example: "Make $40,000 profit = $6,120 self-employment tax."
    },
    {
      term: "Quarterly Estimated Taxes",
      definition: "Tax payments made four times per year (April, June, September, January). Required when you're self-employed to avoid penalties.",
      example: "Expect $20,000 annual profit = pay ~$5,000 quarterly ($1,250 each time)."
    },
    {
      term: "Tax Rate",
      definition: "Percentage of income paid in taxes. Includes federal income tax + self-employment tax + state tax (if applicable).",
      example: "Combined 30% tax rate on $50,000 = $15,000 in taxes."
    },
    {
      term: "1099 Form",
      definition: "Tax form showing your business income. You'll receive these if you sell through platforms like eBay, or issue them to contractors you pay.",
      example: "eBay issues 1099-K for sales over $600/year."
    }
  ];

  const operationalTerms = [
    {
      term: "Show Circuit",
      definition: "Regular rotation of card shows/venues you attend. Building a circuit creates recurring revenue opportunities.",
      example: "Monthly show in your city + bi-weekly regional show = your show circuit."
    },
    {
      term: "Table Cost / Booth Fee",
      definition: "Cost to rent table space at a card show. Major business expense to factor into pricing.",
      example: "$50-$100 per table depending on show size and location."
    },
    {
      term: "Graded Cards",
      definition: "Cards professionally authenticated and condition-graded by companies like PSA or Beckett. Worth more but cost money to grade.",
      example: "Raw card worth $50, PSA 10 same card worth $200."
    },
    {
      term: "Cash Velocity",
      definition: "How quickly you turn inventory into cash and reinvest. Fast velocity = more profit cycles = more total profit.",
      example: "Turn $1,000 inventory monthly = 12 cycles/year vs. once/year = 1 cycle."
    },
    {
      term: "Comps / Comparable Sales",
      definition: "Recent sales of similar cards used to determine market value. Check eBay sold listings for comps.",
      example: "Check eBay sold listings for same player/year/condition to price your card."
    }
  ];

  return (
    <div className="min-h-screen bg-background p-4 pb-24 md:pb-8">
      <div className="max-w-4xl mx-auto space-y-6">
        <PageHeader
          title="Business Glossary"
          subtitle="Essential terms every card trader should know"
          backTo="/dashboard"
        />

        {/* Introduction */}
        <Card className="p-6 bg-card border-border shadow-md">
          <div className="flex items-start gap-4">
            <div className="bg-primary/10 p-3 rounded-lg shrink-0">
              <FileText className="h-6 w-6 text-primary" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-card-foreground mb-2">
                Understanding Business Terms
              </h2>
              <p className="text-card-foreground/80 leading-relaxed">
                Running a card trading business requires understanding key financial and operational terms. 
                This glossary breaks down essential concepts in plain language with practical examples 
                specific to your business.
              </p>
            </div>
          </div>
        </Card>

        {/* Financial Terms */}
        <div>
          <SectionHeading title="Financial Terms" icon={DollarSign} />
          <div className="space-y-4">
            {financialTerms.map((item, index) => (
              <Card key={index} className="p-5 bg-card border-border shadow-md">
                <h3 className="text-lg font-bold text-card-foreground mb-2">
                  {item.term}
                </h3>
                <p className="text-sm text-card-foreground/80 mb-3">
                  {item.definition}
                </p>
                <div className="bg-primary/5 p-3 rounded-lg border-l-4 border-primary">
                  <p className="text-sm text-card-foreground">
                    <span className="font-semibold text-card-foreground">Example: </span>
                    {item.example}
                  </p>
                </div>
              </Card>
            ))}
          </div>
        </div>

        {/* Inventory Terms */}
        <div>
          <SectionHeading title="Inventory Terms" icon={Package} />
          <div className="space-y-4">
            {inventoryTerms.map((item, index) => (
              <Card key={index} className="p-5 bg-card border-border shadow-md">
                <h3 className="text-lg font-bold text-card-foreground mb-2">
                  {item.term}
                </h3>
                <p className="text-sm text-card-foreground/80 mb-3">
                  {item.definition}
                </p>
                <div className="bg-primary/5 p-3 rounded-lg border-l-4 border-primary">
                  <p className="text-sm text-card-foreground">
                    <span className="font-semibold text-card-foreground">Example: </span>
                    {item.example}
                  </p>
                </div>
              </Card>
            ))}
          </div>
        </div>

        {/* Tax & Accounting Terms */}
        <div>
          <SectionHeading title="Tax & Accounting Terms" icon={Calculator} />
          <div className="space-y-4">
            {taxTerms.map((item, index) => (
              <Card key={index} className="p-5 bg-card border-border shadow-md">
                <h3 className="text-lg font-bold text-card-foreground mb-2">
                  {item.term}
                </h3>
                <p className="text-sm text-card-foreground/80 mb-3">
                  {item.definition}
                </p>
                <div className="bg-primary/5 p-3 rounded-lg border-l-4 border-primary">
                  <p className="text-sm text-card-foreground">
                    <span className="font-semibold text-card-foreground">Example: </span>
                    {item.example}
                  </p>
                </div>
              </Card>
            ))}
          </div>
        </div>

        {/* Operational Terms */}
        <div>
          <SectionHeading title="Operational Terms" icon={Briefcase} />
          <div className="space-y-4">
            {operationalTerms.map((item, index) => (
              <Card key={index} className="p-5 bg-card border-border shadow-md">
                <h3 className="text-lg font-bold text-card-foreground mb-2">
                  {item.term}
                </h3>
                <p className="text-sm text-card-foreground/80 mb-3">
                  {item.definition}
                </p>
                <div className="bg-primary/5 p-3 rounded-lg border-l-4 border-primary">
                  <p className="text-sm text-card-foreground">
                    <span className="font-semibold text-card-foreground">Example: </span>
                    {item.example}
                  </p>
                </div>
              </Card>
            ))}
          </div>
        </div>

        {/* Key Distinctions */}
        <Card className="p-6 bg-card border-border shadow-md border-l-4 border-l-primary">
          <h3 className="text-lg font-bold text-card-foreground mb-3">
            Critical Distinction: Business Revenue vs. Personal Income
          </h3>
          <p className="text-sm text-card-foreground/80 mb-4">
            This is the most important concept for new business owners to understand:
          </p>
          <div className="space-y-3">
            <div className="bg-muted/30 p-4 rounded-lg">
              <div className="font-semibold text-card-foreground mb-1">Business Revenue</div>
              <p className="text-sm text-card-foreground/70">
                Total money your business generates from all sales. This money belongs to the business and 
                must cover inventory costs, expenses, taxes, and future growth.
              </p>
            </div>
            <div className="bg-muted/30 p-4 rounded-lg">
              <div className="font-semibold text-card-foreground mb-1">Personal Income (Owner's Draw)</div>
              <p className="text-sm text-card-foreground/70">
                Money you take from the business for personal expenses (your "salary"). This is usually much 
                less than business revenue. Must account for taxes, health insurance, and personal expenses.
              </p>
            </div>
          </div>
          <div className="mt-4 p-4 bg-primary/5 rounded-lg border border-primary/20">
            <p className="text-sm text-card-foreground font-medium">
              Example: If your goal is $4,000 monthly personal income, your business might need to generate 
              $8,000-$10,000 monthly revenue to cover inventory, expenses, taxes, and provide that income.
            </p>
          </div>
        </Card>

        {/* Next Steps */}
        <Card className="p-6 bg-card border-border shadow-md">
          <h3 className="text-lg font-bold text-card-foreground mb-3">Ready to Apply These Concepts?</h3>
          <p className="text-sm text-card-foreground/80 mb-4">
            Now that you understand these key terms, use them to set realistic goals and track your business performance.
          </p>
          <div className="flex flex-wrap gap-3">
            <Button onClick={() => navigate("/goals/business-model")} variant="default">
              Learn Business Model
            </Button>
            <Button onClick={() => navigate("/goals/personal")} variant="outline">
              Set Personal Goals
            </Button>
            <Button onClick={() => navigate("/dashboard")} variant="outline">
              View Dashboard
            </Button>
          </div>
        </Card>
      </div>
    </div>
  );
};

export default Glossary;
